/*
 * Catalytic SDK API
 *  ## API for the Catalytic SDK 
 *
 * The version of the OpenAPI document: v1.0.0
 * Contact: developers@catalytic.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.catalytic.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets InstanceStepStatus
 */
@JsonAdapter(InstanceStepStatus.Adapter.class)
public enum InstanceStepStatus {
  
  PENDING("pending"),
  
  ACTIVE("active"),
  
  COMPLETED("completed"),
  
  CANCELLED("cancelled"),
  
  SNOOZED("snoozed"),
  
  SKIPPED("skipped"),
  
  ERROR("error");

  private String value;

  InstanceStepStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static InstanceStepStatus fromValue(String value) {
    for (InstanceStepStatus b : InstanceStepStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<InstanceStepStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final InstanceStepStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public InstanceStepStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return InstanceStepStatus.fromValue(value);
    }
  }
}

