/*
 * Catalytic SDK API
 *  ## API for the Catalytic SDK 
 *
 * The version of the OpenAPI document: v1.0.0
 * Contact: developers@catalytic.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.catalytic.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.catalytic.sdk.model.Field;
import org.catalytic.sdk.model.InstanceStepStatus;

/**
 * InstanceStep
 */

public class InstanceStep {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private UUID id;

  public static final String SERIALIZED_NAME_INSTANCE_ID = "instanceId";
  @SerializedName(SERIALIZED_NAME_INSTANCE_ID)
  private UUID instanceId;

  public static final String SERIALIZED_NAME_PUSHBOT_ID = "pushbotId";
  @SerializedName(SERIALIZED_NAME_PUSHBOT_ID)
  private UUID pushbotId;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_TEAM_NAME = "teamName";
  @SerializedName(SERIALIZED_NAME_TEAM_NAME)
  private String teamName;

  public static final String SERIALIZED_NAME_POSITION = "position";
  @SerializedName(SERIALIZED_NAME_POSITION)
  private Integer position;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private InstanceStepStatus status;

  public static final String SERIALIZED_NAME_ASSIGNED_TO = "assignedTo";
  @SerializedName(SERIALIZED_NAME_ASSIGNED_TO)
  private String assignedTo;

  public static final String SERIALIZED_NAME_OUTPUT_FIELDS = "outputFields";
  @SerializedName(SERIALIZED_NAME_OUTPUT_FIELDS)
  private List<Field> outputFields = null;


  public InstanceStep id(UUID id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(required = true, value = "")

  public UUID getId() {
    return id;
  }


  public void setId(UUID id) {
    this.id = id;
  }


  public InstanceStep instanceId(UUID instanceId) {
    
    this.instanceId = instanceId;
    return this;
  }

   /**
   * Get instanceId
   * @return instanceId
  **/
  @ApiModelProperty(required = true, value = "")

  public UUID getInstanceId() {
    return instanceId;
  }


  public void setInstanceId(UUID instanceId) {
    this.instanceId = instanceId;
  }


  public InstanceStep pushbotId(UUID pushbotId) {
    
    this.pushbotId = pushbotId;
    return this;
  }

   /**
   * Get pushbotId
   * @return pushbotId
  **/
  @ApiModelProperty(required = true, value = "")

  public UUID getPushbotId() {
    return pushbotId;
  }


  public void setPushbotId(UUID pushbotId) {
    this.pushbotId = pushbotId;
  }


  public InstanceStep name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public InstanceStep teamName(String teamName) {
    
    this.teamName = teamName;
    return this;
  }

   /**
   * Get teamName
   * @return teamName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "")

  public String getTeamName() {
    return teamName;
  }


  public void setTeamName(String teamName) {
    this.teamName = teamName;
  }


  public InstanceStep position(Integer position) {
    
    this.position = position;
    return this;
  }

   /**
   * Get position
   * @return position
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getPosition() {
    return position;
  }


  public void setPosition(Integer position) {
    this.position = position;
  }


  public InstanceStep description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public InstanceStep status(InstanceStepStatus status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public InstanceStepStatus getStatus() {
    return status;
  }


  public void setStatus(InstanceStepStatus status) {
    this.status = status;
  }


  public InstanceStep assignedTo(String assignedTo) {
    
    this.assignedTo = assignedTo;
    return this;
  }

   /**
   * Get assignedTo
   * @return assignedTo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAssignedTo() {
    return assignedTo;
  }


  public void setAssignedTo(String assignedTo) {
    this.assignedTo = assignedTo;
  }


  public InstanceStep outputFields(List<Field> outputFields) {
    
    this.outputFields = outputFields;
    return this;
  }

  public InstanceStep addOutputFieldsItem(Field outputFieldsItem) {
    if (this.outputFields == null) {
      this.outputFields = new ArrayList<>();
    }
    this.outputFields.add(outputFieldsItem);
    return this;
  }

   /**
   * Get outputFields
   * @return outputFields
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Field> getOutputFields() {
    return outputFields;
  }


  public void setOutputFields(List<Field> outputFields) {
    this.outputFields = outputFields;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InstanceStep instanceStep = (InstanceStep) o;
    return Objects.equals(this.id, instanceStep.id) &&
        Objects.equals(this.instanceId, instanceStep.instanceId) &&
        Objects.equals(this.pushbotId, instanceStep.pushbotId) &&
        Objects.equals(this.name, instanceStep.name) &&
        Objects.equals(this.teamName, instanceStep.teamName) &&
        Objects.equals(this.position, instanceStep.position) &&
        Objects.equals(this.description, instanceStep.description) &&
        Objects.equals(this.status, instanceStep.status) &&
        Objects.equals(this.assignedTo, instanceStep.assignedTo) &&
        Objects.equals(this.outputFields, instanceStep.outputFields);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, instanceId, pushbotId, name, teamName, position, description, status, assignedTo, outputFields);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InstanceStep {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    instanceId: ").append(toIndentedString(instanceId)).append("\n");
    sb.append("    pushbotId: ").append(toIndentedString(pushbotId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    teamName: ").append(toIndentedString(teamName)).append("\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    assignedTo: ").append(toIndentedString(assignedTo)).append("\n");
    sb.append("    outputFields: ").append(toIndentedString(outputFields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

