/*
 * Catalytic SDK API
 *  ## API for the Catalytic SDK 
 *
 * The version of the OpenAPI document: v1.0.0
 * Contact: developers@catalytic.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.catalytic.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PagingOptions
 */

public class PagingOptions {
  public static final String SERIALIZED_NAME_SIZE = "size";
  @SerializedName(SERIALIZED_NAME_SIZE)
  private Integer size;

  public static final String SERIALIZED_NAME_PAGE_TOKEN = "pageToken";
  @SerializedName(SERIALIZED_NAME_PAGE_TOKEN)
  private String pageToken;

  public static final String SERIALIZED_NAME_GET_ALL_RESULTS = "getAllResults";
  @SerializedName(SERIALIZED_NAME_GET_ALL_RESULTS)
  private Boolean getAllResults;


  public PagingOptions size(Integer size) {
    
    this.size = size;
    return this;
  }

   /**
   * Get size
   * @return size
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getSize() {
    return size;
  }


  public void setSize(Integer size) {
    this.size = size;
  }


  public PagingOptions pageToken(String pageToken) {
    
    this.pageToken = pageToken;
    return this;
  }

   /**
   * Get pageToken
   * @return pageToken
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPageToken() {
    return pageToken;
  }


  public void setPageToken(String pageToken) {
    this.pageToken = pageToken;
  }


  public PagingOptions getAllResults(Boolean getAllResults) {
    
    this.getAllResults = getAllResults;
    return this;
  }

   /**
   * Get getAllResults
   * @return getAllResults
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getGetAllResults() {
    return getAllResults;
  }


  public void setGetAllResults(Boolean getAllResults) {
    this.getAllResults = getAllResults;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PagingOptions pagingOptions = (PagingOptions) o;
    return Objects.equals(this.size, pagingOptions.size) &&
        Objects.equals(this.pageToken, pagingOptions.pageToken) &&
        Objects.equals(this.getAllResults, pagingOptions.getAllResults);
  }

  @Override
  public int hashCode() {
    return Objects.hash(size, pageToken, getAllResults);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PagingOptions {\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    pageToken: ").append(toIndentedString(pageToken)).append("\n");
    sb.append("    getAllResults: ").append(toIndentedString(getAllResults)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

