/*
 * Catalytic SDK API
 *  ## API for the Catalytic SDK 
 *
 * The version of the OpenAPI document: v1.0.0
 * Contact: developers@catalytic.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.catalytic.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.catalytic.sdk.model.Field;
import org.catalytic.sdk.model.FieldVisibility;
import org.catalytic.sdk.model.InstanceVisibilty;

/**
 * Pushbot
 */

public class Pushbot {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private UUID id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_TEAM_NAME = "teamName";
  @SerializedName(SERIALIZED_NAME_TEAM_NAME)
  private String teamName;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_CATEGORY = "category";
  @SerializedName(SERIALIZED_NAME_CATEGORY)
  private String category;

  public static final String SERIALIZED_NAME_OWNER = "owner";
  @SerializedName(SERIALIZED_NAME_OWNER)
  private String owner;

  public static final String SERIALIZED_NAME_CREATED_BY = "createdBy";
  @SerializedName(SERIALIZED_NAME_CREATED_BY)
  private String createdBy;

  public static final String SERIALIZED_NAME_INPUT_FIELDS = "inputFields";
  @SerializedName(SERIALIZED_NAME_INPUT_FIELDS)
  private List<Field> inputFields = null;

  public static final String SERIALIZED_NAME_IS_PUBLISHED = "isPublished";
  @SerializedName(SERIALIZED_NAME_IS_PUBLISHED)
  private Boolean isPublished;

  public static final String SERIALIZED_NAME_IS_ARCHIVED = "isArchived";
  @SerializedName(SERIALIZED_NAME_IS_ARCHIVED)
  private Boolean isArchived;

  public static final String SERIALIZED_NAME_FIELD_VISIBILITY = "fieldVisibility";
  @SerializedName(SERIALIZED_NAME_FIELD_VISIBILITY)
  private FieldVisibility fieldVisibility;

  public static final String SERIALIZED_NAME_INSTANCE_VISIBILITY = "instanceVisibility";
  @SerializedName(SERIALIZED_NAME_INSTANCE_VISIBILITY)
  private InstanceVisibilty instanceVisibility;

  public static final String SERIALIZED_NAME_ADMIN_USERS = "adminUsers";
  @SerializedName(SERIALIZED_NAME_ADMIN_USERS)
  private List<String> adminUsers = null;

  public static final String SERIALIZED_NAME_STANDARD_USERS = "standardUsers";
  @SerializedName(SERIALIZED_NAME_STANDARD_USERS)
  private List<String> standardUsers = null;

  public static final String SERIALIZED_NAME_TASK_COUNT_LIMIT = "taskCountLimit";
  @SerializedName(SERIALIZED_NAME_TASK_COUNT_LIMIT)
  private Integer taskCountLimit;

  public static final String SERIALIZED_NAME_FIELD_COUNT_LIMIT = "fieldCountLimit";
  @SerializedName(SERIALIZED_NAME_FIELD_COUNT_LIMIT)
  private Integer fieldCountLimit;

  public static final String SERIALIZED_NAME_FIELD_SIZE_LIMIT = "fieldSizeLimit";
  @SerializedName(SERIALIZED_NAME_FIELD_SIZE_LIMIT)
  private Integer fieldSizeLimit;

  public static final String SERIALIZED_NAME_FIELD_TOTAL_SIZE_LIMIT = "fieldTotalSizeLimit";
  @SerializedName(SERIALIZED_NAME_FIELD_TOTAL_SIZE_LIMIT)
  private Integer fieldTotalSizeLimit;

  public static final String SERIALIZED_NAME_DATA_TABLE_ROW_LIMIT = "dataTableRowLimit";
  @SerializedName(SERIALIZED_NAME_DATA_TABLE_ROW_LIMIT)
  private Integer dataTableRowLimit;

  public static final String SERIALIZED_NAME_DATA_TABLE_COLUMN_LIMIT = "dataTableColumnLimit";
  @SerializedName(SERIALIZED_NAME_DATA_TABLE_COLUMN_LIMIT)
  private Integer dataTableColumnLimit;

  public static final String SERIALIZED_NAME_DATA_TABLE_CELL_LIMIT = "dataTableCellLimit";
  @SerializedName(SERIALIZED_NAME_DATA_TABLE_CELL_LIMIT)
  private Integer dataTableCellLimit;


  public Pushbot id(UUID id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(required = true, value = "")

  public UUID getId() {
    return id;
  }


  public void setId(UUID id) {
    this.id = id;
  }


  public Pushbot name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public Pushbot teamName(String teamName) {
    
    this.teamName = teamName;
    return this;
  }

   /**
   * Get teamName
   * @return teamName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "")

  public String getTeamName() {
    return teamName;
  }


  public void setTeamName(String teamName) {
    this.teamName = teamName;
  }


  public Pushbot description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public Pushbot category(String category) {
    
    this.category = category;
    return this;
  }

   /**
   * Get category
   * @return category
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCategory() {
    return category;
  }


  public void setCategory(String category) {
    this.category = category;
  }


  public Pushbot owner(String owner) {
    
    this.owner = owner;
    return this;
  }

   /**
   * Get owner
   * @return owner
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getOwner() {
    return owner;
  }


  public void setOwner(String owner) {
    this.owner = owner;
  }


  public Pushbot createdBy(String createdBy) {
    
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCreatedBy() {
    return createdBy;
  }


  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }


  public Pushbot inputFields(List<Field> inputFields) {
    
    this.inputFields = inputFields;
    return this;
  }

  public Pushbot addInputFieldsItem(Field inputFieldsItem) {
    if (this.inputFields == null) {
      this.inputFields = new ArrayList<>();
    }
    this.inputFields.add(inputFieldsItem);
    return this;
  }

   /**
   * Get inputFields
   * @return inputFields
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Field> getInputFields() {
    return inputFields;
  }


  public void setInputFields(List<Field> inputFields) {
    this.inputFields = inputFields;
  }


  public Pushbot isPublished(Boolean isPublished) {
    
    this.isPublished = isPublished;
    return this;
  }

   /**
   * Get isPublished
   * @return isPublished
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsPublished() {
    return isPublished;
  }


  public void setIsPublished(Boolean isPublished) {
    this.isPublished = isPublished;
  }


  public Pushbot isArchived(Boolean isArchived) {
    
    this.isArchived = isArchived;
    return this;
  }

   /**
   * Get isArchived
   * @return isArchived
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsArchived() {
    return isArchived;
  }


  public void setIsArchived(Boolean isArchived) {
    this.isArchived = isArchived;
  }


  public Pushbot fieldVisibility(FieldVisibility fieldVisibility) {
    
    this.fieldVisibility = fieldVisibility;
    return this;
  }

   /**
   * Get fieldVisibility
   * @return fieldVisibility
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public FieldVisibility getFieldVisibility() {
    return fieldVisibility;
  }


  public void setFieldVisibility(FieldVisibility fieldVisibility) {
    this.fieldVisibility = fieldVisibility;
  }


  public Pushbot instanceVisibility(InstanceVisibilty instanceVisibility) {
    
    this.instanceVisibility = instanceVisibility;
    return this;
  }

   /**
   * Get instanceVisibility
   * @return instanceVisibility
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public InstanceVisibilty getInstanceVisibility() {
    return instanceVisibility;
  }


  public void setInstanceVisibility(InstanceVisibilty instanceVisibility) {
    this.instanceVisibility = instanceVisibility;
  }


  public Pushbot adminUsers(List<String> adminUsers) {
    
    this.adminUsers = adminUsers;
    return this;
  }

  public Pushbot addAdminUsersItem(String adminUsersItem) {
    if (this.adminUsers == null) {
      this.adminUsers = new ArrayList<>();
    }
    this.adminUsers.add(adminUsersItem);
    return this;
  }

   /**
   * Get adminUsers
   * @return adminUsers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getAdminUsers() {
    return adminUsers;
  }


  public void setAdminUsers(List<String> adminUsers) {
    this.adminUsers = adminUsers;
  }


  public Pushbot standardUsers(List<String> standardUsers) {
    
    this.standardUsers = standardUsers;
    return this;
  }

  public Pushbot addStandardUsersItem(String standardUsersItem) {
    if (this.standardUsers == null) {
      this.standardUsers = new ArrayList<>();
    }
    this.standardUsers.add(standardUsersItem);
    return this;
  }

   /**
   * Get standardUsers
   * @return standardUsers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getStandardUsers() {
    return standardUsers;
  }


  public void setStandardUsers(List<String> standardUsers) {
    this.standardUsers = standardUsers;
  }


  public Pushbot taskCountLimit(Integer taskCountLimit) {
    
    this.taskCountLimit = taskCountLimit;
    return this;
  }

   /**
   * Get taskCountLimit
   * @return taskCountLimit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getTaskCountLimit() {
    return taskCountLimit;
  }


  public void setTaskCountLimit(Integer taskCountLimit) {
    this.taskCountLimit = taskCountLimit;
  }


  public Pushbot fieldCountLimit(Integer fieldCountLimit) {
    
    this.fieldCountLimit = fieldCountLimit;
    return this;
  }

   /**
   * Get fieldCountLimit
   * @return fieldCountLimit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getFieldCountLimit() {
    return fieldCountLimit;
  }


  public void setFieldCountLimit(Integer fieldCountLimit) {
    this.fieldCountLimit = fieldCountLimit;
  }


  public Pushbot fieldSizeLimit(Integer fieldSizeLimit) {
    
    this.fieldSizeLimit = fieldSizeLimit;
    return this;
  }

   /**
   * Get fieldSizeLimit
   * @return fieldSizeLimit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getFieldSizeLimit() {
    return fieldSizeLimit;
  }


  public void setFieldSizeLimit(Integer fieldSizeLimit) {
    this.fieldSizeLimit = fieldSizeLimit;
  }


  public Pushbot fieldTotalSizeLimit(Integer fieldTotalSizeLimit) {
    
    this.fieldTotalSizeLimit = fieldTotalSizeLimit;
    return this;
  }

   /**
   * Get fieldTotalSizeLimit
   * @return fieldTotalSizeLimit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getFieldTotalSizeLimit() {
    return fieldTotalSizeLimit;
  }


  public void setFieldTotalSizeLimit(Integer fieldTotalSizeLimit) {
    this.fieldTotalSizeLimit = fieldTotalSizeLimit;
  }


  public Pushbot dataTableRowLimit(Integer dataTableRowLimit) {
    
    this.dataTableRowLimit = dataTableRowLimit;
    return this;
  }

   /**
   * Get dataTableRowLimit
   * @return dataTableRowLimit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getDataTableRowLimit() {
    return dataTableRowLimit;
  }


  public void setDataTableRowLimit(Integer dataTableRowLimit) {
    this.dataTableRowLimit = dataTableRowLimit;
  }


  public Pushbot dataTableColumnLimit(Integer dataTableColumnLimit) {
    
    this.dataTableColumnLimit = dataTableColumnLimit;
    return this;
  }

   /**
   * Get dataTableColumnLimit
   * @return dataTableColumnLimit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getDataTableColumnLimit() {
    return dataTableColumnLimit;
  }


  public void setDataTableColumnLimit(Integer dataTableColumnLimit) {
    this.dataTableColumnLimit = dataTableColumnLimit;
  }


  public Pushbot dataTableCellLimit(Integer dataTableCellLimit) {
    
    this.dataTableCellLimit = dataTableCellLimit;
    return this;
  }

   /**
   * Get dataTableCellLimit
   * @return dataTableCellLimit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getDataTableCellLimit() {
    return dataTableCellLimit;
  }


  public void setDataTableCellLimit(Integer dataTableCellLimit) {
    this.dataTableCellLimit = dataTableCellLimit;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Pushbot pushbot = (Pushbot) o;
    return Objects.equals(this.id, pushbot.id) &&
        Objects.equals(this.name, pushbot.name) &&
        Objects.equals(this.teamName, pushbot.teamName) &&
        Objects.equals(this.description, pushbot.description) &&
        Objects.equals(this.category, pushbot.category) &&
        Objects.equals(this.owner, pushbot.owner) &&
        Objects.equals(this.createdBy, pushbot.createdBy) &&
        Objects.equals(this.inputFields, pushbot.inputFields) &&
        Objects.equals(this.isPublished, pushbot.isPublished) &&
        Objects.equals(this.isArchived, pushbot.isArchived) &&
        Objects.equals(this.fieldVisibility, pushbot.fieldVisibility) &&
        Objects.equals(this.instanceVisibility, pushbot.instanceVisibility) &&
        Objects.equals(this.adminUsers, pushbot.adminUsers) &&
        Objects.equals(this.standardUsers, pushbot.standardUsers) &&
        Objects.equals(this.taskCountLimit, pushbot.taskCountLimit) &&
        Objects.equals(this.fieldCountLimit, pushbot.fieldCountLimit) &&
        Objects.equals(this.fieldSizeLimit, pushbot.fieldSizeLimit) &&
        Objects.equals(this.fieldTotalSizeLimit, pushbot.fieldTotalSizeLimit) &&
        Objects.equals(this.dataTableRowLimit, pushbot.dataTableRowLimit) &&
        Objects.equals(this.dataTableColumnLimit, pushbot.dataTableColumnLimit) &&
        Objects.equals(this.dataTableCellLimit, pushbot.dataTableCellLimit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, teamName, description, category, owner, createdBy, inputFields, isPublished, isArchived, fieldVisibility, instanceVisibility, adminUsers, standardUsers, taskCountLimit, fieldCountLimit, fieldSizeLimit, fieldTotalSizeLimit, dataTableRowLimit, dataTableColumnLimit, dataTableCellLimit);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Pushbot {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    teamName: ").append(toIndentedString(teamName)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    inputFields: ").append(toIndentedString(inputFields)).append("\n");
    sb.append("    isPublished: ").append(toIndentedString(isPublished)).append("\n");
    sb.append("    isArchived: ").append(toIndentedString(isArchived)).append("\n");
    sb.append("    fieldVisibility: ").append(toIndentedString(fieldVisibility)).append("\n");
    sb.append("    instanceVisibility: ").append(toIndentedString(instanceVisibility)).append("\n");
    sb.append("    adminUsers: ").append(toIndentedString(adminUsers)).append("\n");
    sb.append("    standardUsers: ").append(toIndentedString(standardUsers)).append("\n");
    sb.append("    taskCountLimit: ").append(toIndentedString(taskCountLimit)).append("\n");
    sb.append("    fieldCountLimit: ").append(toIndentedString(fieldCountLimit)).append("\n");
    sb.append("    fieldSizeLimit: ").append(toIndentedString(fieldSizeLimit)).append("\n");
    sb.append("    fieldTotalSizeLimit: ").append(toIndentedString(fieldTotalSizeLimit)).append("\n");
    sb.append("    dataTableRowLimit: ").append(toIndentedString(dataTableRowLimit)).append("\n");
    sb.append("    dataTableColumnLimit: ").append(toIndentedString(dataTableColumnLimit)).append("\n");
    sb.append("    dataTableCellLimit: ").append(toIndentedString(dataTableCellLimit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

