/*
 * Catalytic SDK API
 *  ## API for the Catalytic SDK 
 *
 * The version of the OpenAPI document: v1.0.0
 * Contact: developers@catalytic.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.catalytic.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;

/**
 * PushbotExportRequest
 */

public class PushbotExportRequest {
  public static final String SERIALIZED_NAME_PUSHBOT_ID = "pushbotId";
  @SerializedName(SERIALIZED_NAME_PUSHBOT_ID)
  private UUID pushbotId;

  public static final String SERIALIZED_NAME_PASSWORD = "password";
  @SerializedName(SERIALIZED_NAME_PASSWORD)
  private String password;


  public PushbotExportRequest pushbotId(UUID pushbotId) {
    
    this.pushbotId = pushbotId;
    return this;
  }

   /**
   * Get pushbotId
   * @return pushbotId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public UUID getPushbotId() {
    return pushbotId;
  }


  public void setPushbotId(UUID pushbotId) {
    this.pushbotId = pushbotId;
  }


  public PushbotExportRequest password(String password) {
    
    this.password = password;
    return this;
  }

   /**
   * Get password
   * @return password
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPassword() {
    return password;
  }


  public void setPassword(String password) {
    this.password = password;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PushbotExportRequest pushbotExportRequest = (PushbotExportRequest) o;
    return Objects.equals(this.pushbotId, pushbotExportRequest.pushbotId) &&
        Objects.equals(this.password, pushbotExportRequest.password);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pushbotId, password);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PushbotExportRequest {\n");
    sb.append("    pushbotId: ").append(toIndentedString(pushbotId)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

