/*
 * Catalytic SDK API
 *  ## API for the Catalytic SDK 
 *
 * The version of the OpenAPI document: v1.0.0
 * Contact: developers@catalytic.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.catalytic.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * WaitForCredentialsApprovalRequest
 */

public class WaitForCredentialsApprovalRequest {
  public static final String SERIALIZED_NAME_TOKEN = "token";
  @SerializedName(SERIALIZED_NAME_TOKEN)
  private String token;

  public static final String SERIALIZED_NAME_WAIT_TIME_MILLIS = "waitTimeMillis";
  @SerializedName(SERIALIZED_NAME_WAIT_TIME_MILLIS)
  private Integer waitTimeMillis;


  public WaitForCredentialsApprovalRequest token(String token) {
    
    this.token = token;
    return this;
  }

   /**
   * Get token
   * @return token
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "")

  public String getToken() {
    return token;
  }


  public void setToken(String token) {
    this.token = token;
  }


  public WaitForCredentialsApprovalRequest waitTimeMillis(Integer waitTimeMillis) {
    
    this.waitTimeMillis = waitTimeMillis;
    return this;
  }

   /**
   * Get waitTimeMillis
   * @return waitTimeMillis
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getWaitTimeMillis() {
    return waitTimeMillis;
  }


  public void setWaitTimeMillis(Integer waitTimeMillis) {
    this.waitTimeMillis = waitTimeMillis;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WaitForCredentialsApprovalRequest waitForCredentialsApprovalRequest = (WaitForCredentialsApprovalRequest) o;
    return Objects.equals(this.token, waitForCredentialsApprovalRequest.token) &&
        Objects.equals(this.waitTimeMillis, waitForCredentialsApprovalRequest.waitTimeMillis);
  }

  @Override
  public int hashCode() {
    return Objects.hash(token, waitTimeMillis);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WaitForCredentialsApprovalRequest {\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    waitTimeMillis: ").append(toIndentedString(waitTimeMillis)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

