# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        java: [8, 9, 10, 11, 12, 13, 14-ea]

    name: Java ${{ matrix.java}} build
    steps:
    # Checkout the code
    - uses: actions/checkout@v2

    # Setup JDK version
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}

    # Get dependency cache
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}

    # Grant permissions to gradlew
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Build and test
    - name: Build with Gradle
      run: ./gradlew build

    # Publish code coverage
    - name: Test and publish code coverage
      uses: paambaati/codeclimate-action@v2.6.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        JACOCO_SOURCE_PATH: "${{ github.workspace }}/src/main/java"
      with:
        coverageCommand: ./gradlew jacocoTestReport
        coverageLocations: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
